version: "3.8"

services:

  server:
    image: "swaiku/tpi_server:latest"
    container_name: "prinj_tpi_server"
    restart: "always"
    depends_on:
      - db
    ports:
      - "6464:8080"
    environment:
      SPRING_APPLICATION_JSON: '{ 
        "spring.datasource.url" : "jdbc:mysql://db:3306/$MYSQL_DATABASE?zeroDateTimeBehavior=convertToNull", 
        "spring.datasource.username" : "$MYSQL_USER", 
        "spring.datasource.password" : "$MYSQL_ROOT_PASSWORD", 
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.datasource.testWhileIdle" : "true",
        "spring.datasource.validationQuery" : "SELECT 1", 
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    links:
      - db

  db:
    image: "mariadb:lts"
    container_name: "prinj_tpi_db"
    restart: 'always'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
